In [2]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])
\
print(x*y)

tensor([10.,  3.])


In [9]:
x = torch.zeros([2,5])

print(x)
print("shape of x is ", x.shape)
print("doctype of x is" ,x.dtype)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
shape of x is  torch.Size([2, 5])
doctype of x is torch.float32


In [11]:
y= torch.rand([2,5])
print(y)

tensor([[0.6273, 0.5360, 0.7244, 0.2551, 0.1627],
        [0.4665, 0.6130, 0.7258, 0.7053, 0.8793]])


In [12]:
y.view([1,10])

tensor([[0.6273, 0.5360, 0.7244, 0.2551, 0.1627, 0.4665, 0.6130, 0.7258, 0.7053,
         0.8793]])

In [13]:
y

tensor([[0.6273, 0.5360, 0.7244, 0.2551, 0.1627],
        [0.4665, 0.6130, 0.7258, 0.7053, 0.8793]])